apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app
  namespace: argocd  # ArgoCD watches this namespace for Application CRs
spec:
  project: default

  source:
    repoURL: 'https://github.com/crestrepop81/ArgoCD_first.git'
    targetRevision: HEAD
    path: .  # assuming the manifests are in the root directory

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # change if your app should deploy to a different namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
